---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::LanguageExtensions

Description:
  Deploys subnets according to provided parameters

Parameters:
  SubnetCIDRs:
    Type: CommaDelimitedList
  SubnetAZs:
    Type: CommaDelimitedList
  VPCId:
    Type: String
  PublicSubnets:
    Type: CommaDelimitedList
  Region:
    Type: String
    Description: Current deployment region
    Default: us-east-2
    ConstraintDescription: Must be a valid AWS region.

Resources:
  Subnets:
    Fn::ForEach::SubnetLoop:
      - CIDRIndex
      - !Ref SubnetCIDRs
      - Subnet${CIDRIndex}:
          Type: AWS::EC2::Subnet
          Properties:
            VpcId: !Ref VPCId
            CidrBlock: !Select
              - !Sub "${CIDRIndex}"
              - !Ref SubnetCIDRs
            AvailabilityZone: !Select
              - !Sub "${CIDRIndex}"
              - !Ref SubnetAZs
            MapPublicIpOnLaunch: !Select
              - !Sub "${CIDRIndex}"
              - !Ref PublicSubnets
            Tags:
              - Key: Name
                Value: !Sub "subnet-${Region}-${CIDRIndex}"
